name: AAVM Linux CI

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cxx: [g++-7, g++-8, g++-9, g++-10, 
              clang++-8, clang++-9, clang++-10]
        build-type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      env:
        CXX: ${{matrix.cxx}}
      run: |
        cmake -B ${{github.workspace}}/build \
              -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{matrix.build-type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build-type}}
