name: linux

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        cxx: [g++-9, g++-10, clang++-10, clang++-11]
        build-type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      env:
        CXX: ${{matrix.cxx}}
      run: |
        cmake -B "${{github.workspace}}/build" -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{matrix.build-type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build-type}}
