name: macos 

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.name}} ${{matrix.build-type}}
    runs-on: ${{matrix.os}} 
    strategy:
      matrix:
        os: [macos-latest]
        build-type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        cmake -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{matrix.build-type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build-type}}
