name: mingw

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ${{matrix.os}} 
    strategy:
      matrix:
        os: [windows-latest]
        build-type: [Debug, Release]
        msystem: [MINGW64, MINGW32]
        arch: [x86_64, i686]
        cc: [gcc, clang]
        cxx: [g++, clang++]
        exclude:
          - msystem: MINGW64
            arch: i686
          - msystem: MINGW32
            arch: x86_64
          - cc: gcc
            cxx: clang++
          - cc: clang
            cxx: g++
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.msystem}}
        update: true
        install: >-
          base-devel
          git
          mingw-w64-${{matrix.arch}}-${{matrix.cc}}
          mingw-w64-${{matrix.arch}}-ninja
          mingw-w64-${{matrix.arch}}-cmake

    - name: Configure CMake
      env:
        CXX: ${{matrix.cxx}}
      run: |
        cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{matrix.build-type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build-type}}
