name: mingw

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ${{matrix.os}} 
    strategy:
      matrix:
        os: [windows-latest]
        build-type: [Debug, Release]
        platform:
          - { msystem: MINGW64, arch: x86_64 }
          - { msystem: MINGW32, arch: i686 }
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.platform.msystem}}
        update: true
        install: >-
          base-devel
          git
          mingw-w64-${{matrix.platform.arch}}-${{matrix.compiler.cc}}
          mingw-w64-${{matrix.platform.arch}}-ninja
          mingw-w64-${{matrix.platform.arch}}-cmake
          mingw-w64-${{matrix.platform.arch}}-libc++
          mingw-w64-${{matrix.platform.arch}}-libc++abi

    - name: Configure CMake
      env:
        CXX: ${{matrix.compiler.cxx}}
      run: |
        cmake -B "${{github.workspace}}/build" -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{matrix.build-type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build-type}}
