name: windows

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.name}} on ${{matrix.os}} (${{matrix.platform}}, ${{matrix.build-type}})
    runs-on: ${{matrix.os}} 
    strategy:
      matrix:
        os: [windows-2016, windows-2019]
        build-type: [Debug, Release]
        platform: [Win32, x64]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        cmake -B "${{github.workspace}}/build" -A ${{matrix.platform}} -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{matrix.build-type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build-type}}
